title: Gio Love
description: Stuff I love about Gio
show_downloads: false
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
